;;; nord-theme.el --- An arctic, north-bluish clean and elegant theme

;; Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com> (https://www.arcticicestudio.com)
;; Copyright (C) 2016-present Sven Greb <development@svengreb.de> (https://www.svengreb.de)

;; Title: Nord Theme
;; Project: nord-emacs
;; Version: 0.4.0
;; URL: https://github.com/arcticicestudio/nord-emacs
;; Author: Arctic Ice Studio <development@arcticicestudio.com>
;; Package-Requires: ((emacs "24"))
;; License: MIT

;;; Commentary:

;; Nord is a 16 colorspace theme build to run in GUI- and terminal
;; mode with support for many third-party syntax- and UI packages.

;;; References:
;; Awesome Emacs
;;   https://github.com/emacs-tw/awesome-emacs
;; GNU ELPA
;;   https://elpa.gnu.org
;; GNU Emacs
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Creating-Custom-Themes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Faces.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Standard-Faces.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Face-Customization.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Feature-Testing.html
;; marmalade repo
;;   https://marmalade-repo.org
;; MELPA
;;   https://melpa.org
;;   https://stable.melpa.org

;;; Code:

(unless (>= emacs-major-version 24)
  (error "Nord theme requires Emacs 24 or later!"))

(deftheme nord "An arctic, north-bluish clean and elegant theme")

(defgroup nord nil
  "Nord theme customizations.
  The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom nord-comment-brightness 10
  "Allows to define a custom comment color brightness with percentage adjustments from 0% - 20%.
  As of version 0.4.0, this variable is obsolete/deprecated and has no effect anymore and will be removed in version 1.0.0!
  The comment color brightness has been increased by 10% by default.
  Please see https://github.com/arcticicestudio/nord-emacs/issues/73 for more details."
  :type 'integer
  :group 'nord)

(make-obsolete-variable
 'nord-comment-brightness
 "The custom color brightness feature has been deprecated and will be removed in version 1.0.0!
  The comment color brightness has been increased by 10% by default.
  Please see https://github.com/arcticicestudio/nord-emacs/issues/73 for more details."
 "0.4.0")

(defcustom nord-region-highlight nil
  "Allows to set a region highlight style based on the Nord components.
  Valid styles are
    - 'snowstorm' - Uses 'nord0' as foreground- and 'nord4' as background color
    - 'frost' - Uses 'nord0' as foreground- and 'nord8' as background color"
  :type 'string
  :group 'nord)

(defcustom nord-uniform-mode-lines nil
  "Enables uniform activate- and inactive mode lines using 'nord3' as background."
  :type 'boolean
  :group 'nord)

(setq nord-theme--brightened-comments '("#4c566a" "#4e586d" "#505b70" "#525d73" "#556076" "#576279" "#59647c" "#5b677f" "#5d6982" "#5f6c85" "#616e88" "#63718b" "#66738e" "#687591" "#6a7894" "#6d7a96" "#6f7d98" "#72809a" "#75829c" "#78859e" "#7b88a1"))

(defun nord-theme--brightened-comment-color (percent)
  "Returns the brightened comment color for the given percent.
  The value must be greater or equal to 0 and less or equal to 20, otherwise the default 'nord3' color is used.
  As of version 0.4.0, this function is obsolete/deprecated and has no effect anymore and will be removed in version 1.0.0!
  The comment color brightness has been increased by 10% by default.
  Please see https://github.com/arcticicestudio/nord-emacs/issues/73 for more details."
  (nth 10 nord-theme--brightened-comments))

(make-obsolete
 'nord-theme--brightened-comment-color
 "The custom color brightness feature has been deprecated and will be removed in version 1.0.0!\
  The comment color brightness has been increased by 10% by default.\
  Please see https://github.com/arcticicestudio/nord-emacs/issues/73 for more details."
 "0.4.0")

;;;; Color Constants
(let ((class '((class color) (min-colors 89)))
      (nord0 '("#2E3440" . nil))
      (nord1 '("#3B4252" . "black"))
      (nord2 '("#434C5E" . "#434C5E"))
      (nord3 '("#4C566A" . "brightblack"))
      (nord4 '("#D8DEE9" . "#D8DEE9"))
      (nord5 '("#E5E9F0" . "white"))
      (nord6 '("#ECEFF4" . "brightwhite"))
      (nord7 '("#8FBCBB" . "cyan"))
      (nord8 '("#88C0D0" . "brightcyan"))
      (nord9 '("#81A1C1" . "blue"))
      (nord10 '("#5E81AC" . "brightblue"))
      (nord11 '("#BF616A" . "red"))
      (nord12 '("#D08770" . "brightyellow"))
      (nord13 '("#EBCB8B" . "yellow"))
      (nord14 '("#A3BE8C" . "green"))
      (nord15 '("#B48EAD" . "magenta"))
      (nord-annotation '("#D08770" . "brightyellow"))
      (nord-attribute '("#8FBCBB" . "cyan"))
      (nord-class '("#8FBCBB" . "cyan"))
      (nord-comment  `(,(nord-theme--brightened-comment-color nord-comment-brightness) . "brightblack"))
      (nord-escape '("#D08770" . "brightyellow"))
      (nord-method '("#88C0D0" . "brightcyan"))
      (nord-keyword '("#81A1C1" . "blue"))
      (nord-numeric '("#B48EAD" . "magenta"))
      (nord-operator '("#81A1C1" . "blue"))
      (nord-preprocessor '("#5E81AC" . "brightblue"))
      (nord-punctuation '("#D8DEE9" . "#D8DEE9"))
      (nord-regexp '("#EBCB8B" . "yellow"))
      (nord-string '("#A3BE8C" . "green"))
      (nord-tag '("#81A1C1" . "blue"))
      (nord-variable '("#D8DEE9" . "#D8DEE9"))
      (nord-region-highlight-foreground (if (or (string= nord-region-highlight "frost")
                                                (string= nord-region-highlight "snowstorm"))
                                            "#2E3440"
                                          nil))
      (nord-region-highlight-background (cond
                                         ((string= nord-region-highlight "frost") "#88C0D0")
                                         ((string= nord-region-highlight "snowstorm") "#D8DEE9")
                                         (t  "#434C5E")))
      (nord-uniform-mode-lines-background (if nord-uniform-mode-lines "#4C566A" "#3B4252")))

;;;; +------------+
;;;; + Core Faces +
;;;; +------------+
  (custom-theme-set-faces
   'nord
   ;; +--- Base ---+
   `(bold ((,class (:weight bold))
           (((type tty)) (:weight bold))))
   `(bold-italic ((,class (:weight bold :slant italic))
                  (((type tty)) (:weight bold :slant italic))))
   `(default ((,class (:foreground ,(car nord4) :background ,(car nord0)))
              (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord0)))))
   `(error ((,class (:foreground ,(car nord11) :weight bold))
            (((type tty)) (:foreground ,(cdr nord11) :weight bold))))
   `(escape-glyph ((,class (:foreground ,(car nord12)))
                   (((type tty)) (:foreground ,(cdr nord12)))))
   `(font-lock-builtin-face ((,class (:foreground ,(car nord9)))
                             (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-lock-comment-face ((,class (:foreground ,(car nord-comment)))
                             (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,(car nord-comment)))
                                       (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(font-lock-constant-face ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-lock-doc-face ((,class (:foreground ,(car nord-comment)))
                         (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(font-lock-function-name-face ((,class (:foreground ,(car nord8)))
                                   (((type tty)) (:foreground ,(cdr nord8)))))
   `(font-lock-keyword-face ((,class (:foreground ,(car nord9)))
                             (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-lock-negation-char-face ((,class (:foreground ,(car nord9)))
                                   (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-lock-preprocessor-face ((,class (:foreground ,(car nord10) :weight bold))
                                  (((type tty)) (:foreground ,(cdr nord10) :weight bold))))
   `(font-lock-reference-face ((,class (:foreground ,(car nord9)))
                               (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,(car nord13)))
                                          (((type tty)) (:foreground ,(cdr nord13)))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,(car nord13)))
                                          (((type tty)) (:foreground ,(cdr nord13)))))
   `(font-lock-string-face ((,class (:foreground ,(car nord14)))
                            (((type tty)) (:foreground ,(cdr nord14)))))
   `(font-lock-type-face ((,class (:foreground ,(car nord7)))
                          (((type tty)) (:foreground ,(cdr nord7)))))
   `(font-lock-variable-name-face ((,class (:foreground ,(car nord4)))
                                   (((type tty)) (:foreground ,(cdr nord4)))))
   `(font-lock-warning-face ((,class (:foreground ,(car nord13)))
                             (((type tty)) (:foreground ,(cdr nord13)))))
   `(italic ((,class (:slant italic))
             (((type tty)) (:slant italic))))
   `(shadow ((,class (:foreground ,(car nord3)))
             (((type tty)) (:foreground ,(cdr nord3)))))
   `(underline ((,class (:underline t))
                (((type tty)) (:underline t))))
   `(warning ((,class (:foreground ,(car nord13) :weight bold))
              (((type tty)) (:foreground ,(cdr nord13) :weight bold))))

   ;; +--- Syntax ---+
   ;; > C
   `(c-annotation-face ((,class (:foreground ,(car nord-annotation)))
                        (((type tty)) (:foreground ,(cdr nord-annotation)))))

   ;; > diff
   `(diff-added ((,class (:foreground ,(car nord14)))
                 (((type tty)) (:foreground ,(cdr nord14)))))
   `(diff-changed ((,class (:foreground ,(car nord13)))
                   (((type tty)) (:foreground ,(cdr nord13)))))
   `(diff-context ((,class (:inherit default))
                   (((type tty)) (:inherit default))))
   `(diff-file-header ((,class (:foreground ,(car nord8)))
                       (((type tty)) (:foreground ,(cdr nord8)))))
   `(diff-function ((,class (:foreground ,(car nord7)))
                    (((type tty)) (:foreground ,(cdr nord7)))))
   `(diff-header ((,class (:foreground ,(car nord9) :weight bold))
                  (((type tty)) (:foreground ,(cdr nord9) :weight bold))))
   `(diff-hunk-header ((,class (:foreground ,(car nord9) :background ,(car nord0)))
                       (((type tty)) (:foreground ,(cdr nord9) :background ,(cdr nord0)))))
   `(diff-indicator-added ((,class (:foreground ,(car nord14)))
                           (((type tty)) (:foreground ,(cdr nord14)))))
   `(diff-indicator-changed ((,class (:foreground ,(car nord13)))
                             (((type tty)) (:foreground ,(cdr nord13)))))
   `(diff-indicator-removed ((,class (:foreground ,(car nord11)))
                             (((type tty)) (:foreground ,(cdr nord11)))))
   `(diff-nonexistent ((,class (:foreground ,(car nord11)))
                       (((type tty)) (:foreground ,(cdr nord11)))))
   `(diff-refine-added ((,class (:foreground ,(car nord14)))
                        (((type tty)) (:foreground ,(cdr nord14)))))
   `(diff-refine-changed ((,class (:foreground ,(car nord13)))
                          (((type tty)) (:foreground ,(cdr nord13)))))
   `(diff-refine-removed ((,class (:foreground ,(car nord11)))
                          (((type tty)) (:foreground ,(cdr nord11)))))
   `(diff-removed ((,class (:foreground ,(car nord11)))
                   (((type tty)) (:foreground ,(cdr nord11)))))

   ;; +--- UI ---+
   `(border ((,class (:foreground ,(car nord4)))
             (((type tty)) (:foreground ,(cdr nord4)))))
   `(buffer-menu-buffer ((,class (:foreground ,(car nord4) :weight bold))
                         (((type tty)) (:foreground ,(cdr nord4) :weight bold))))
   `(button ((,class (:background ,(car nord0) :foreground ,(car nord8) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
             (((type tty)) (:background ,(cdr nord0) :foreground ,(cdr nord8) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(completions-annotations ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(completions-common-part ((,class (:foreground ,(car nord8) :weight bold))
                              (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(completions-first-difference ((,class (:foreground ,(car nord11)))
                                   (((type tty)) (:foreground ,(cdr nord11)))))
   `(custom-button ((,class (:background ,(car nord0) :foreground ,(car nord8) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
                    (((type tty)) (:background ,(cdr nord0) :foreground ,(cdr nord8) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(custom-button-mouse ((,class (:background ,(car nord4) :foreground ,(car nord0) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
                          (((type tty)) (:background ,(cdr nord4) :foreground ,(cdr nord0) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(custom-button-pressed ((,class (:background ,(car nord6) :foreground ,(car nord0) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
                            (((type tty)) (:background ,(cdr nord6) :foreground ,(cdr nord0) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(custom-button-pressed-unraised ((,class (:background ,(car nord4) :foreground ,(car nord0) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
                                     (((type tty)) (:background ,(cdr nord4) :foreground ,(cdr nord0) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(custom-button-unraised ((,class (:background ,(car nord0) :foreground ,(car nord8) :box (:line-width 2 :color ,(car nord4) :style sunken-button)))
                             (((type tty)) (:background ,(cdr nord0) :foreground ,(cdr nord8) :box (:line-width 2 :color ,(cdr nord4) :style sunken-button)))))
   `(custom-changed ((,class (:foreground ,(car nord13)))
                     (((type tty)) (:foreground ,(cdr nord13)))))
   `(custom-comment ((,class (:foreground ,(car nord-comment)))
                     (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(custom-comment-tag ((,class (:foreground ,(car nord7)))
                         (((type tty)) (:foreground ,(cdr nord7)))))
   `(custom-documentation ((,class (:foreground ,(car nord4)))
                           (((type tty)) (:foreground ,(cdr nord4)))))
   `(custom-group-tag ((,class (:foreground ,(car nord8) :weight bold))
                       (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(custom-group-tag-1 ((,class (:foreground ,(car nord8) :weight bold))
                         (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(custom-invalid ((,class (:foreground ,(car nord11)))
                     (((type tty)) (:foreground ,(cdr nord11)))))
   `(custom-modified ((,class (:foreground ,(car nord13)))
                      (((type tty)) (:foreground ,(cdr nord13)))))
   `(custom-rogue ((,class (:foreground ,(car nord12) :background ,(car nord2)))
                   (((type tty)) (:foreground ,(cdr nord12) :background ,(cdr nord2)))))
   `(custom-saved ((,class (:foreground ,(car nord14)))
                   (((type tty)) (:foreground ,(cdr nord14)))))
   `(custom-set ((,class (:foreground ,(car nord8)))
                 (((type tty)) (:foreground ,(cdr nord8)))))
   `(custom-state ((,class (:foreground ,(car nord14)))
                   (((type tty)) (:foreground ,(cdr nord14)))))
   `(custom-themed ((,class (:foreground ,(car nord8) :background ,(car nord2)))
                    (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord2)))))
   `(cursor ((,class (:background ,(car nord4)))
             (((type tty)) (:background ,(cdr nord4)))))
   `(fringe ((,class (:foreground ,(car nord4) :background ,(car nord0)))
             (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord0)))))
   `(file-name-shadow ((,class (:inherit shadow))
                       (((type tty)) (:inherit shadow))))
   `(header-line ((,class (:foreground ,(car nord4) :background ,(car nord2)))
                  (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord2)))))
   `(help-argument-name ((,class (:foreground ,(car nord8)))
                         (((type tty)) (:foreground ,(cdr nord8)))))
   `(highlight ((,class (:foreground ,(car nord8) :background ,(car nord2)))
                (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord2)))))
   `(hl-line ((,class (:background ,(car nord1)))
              (((type tty)) (:background ,(cdr nord1)))))
   `(info-menu-star ((,class (:foreground ,(car nord9)))
                     (((type tty)) (:foreground ,(cdr nord9)))))
   `(isearch ((,class (:foreground ,(car nord0) :background ,(car nord8)))
              (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord8)))))
   `(isearch-fail ((,class (:foreground ,(car nord11)))
                   (((type tty)) (:foreground ,(cdr nord11)))))
   `(link ((,class (:underline t))
           (((type tty)) (:underline t))))
   `(link-visited ((,class (:underline t))
                   (((type tty)) (:underline t))))
   `(linum ((,class (:foreground ,(car nord3) :background ,(car nord0)))
            (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(linum-relative-current-face ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                                  (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(match ((,class (:inherit isearch))
            (((type tty)) (:inherit isearch))))
   `(message-cited-text ((,class (:foreground ,(car nord4)))
                         (((type tty)) (:foreground ,(cdr nord4)))))
   `(message-header-cc ((,class (:foreground ,(car nord9)))
                        (((type tty)) (:foreground ,(cdr nord9)))))
   `(message-header-name ((,class (:foreground ,(car nord7)))
                          (((type tty)) (:foreground ,(cdr nord7)))))
   `(message-header-newsgroup ((,class (:foreground ,(car nord14)))
                               (((type tty)) (:foreground ,(cdr nord14)))))
   `(message-header-other ((,class (:foreground ,(car nord4)))
                           (((type tty)) (:foreground ,(cdr nord4)))))
   `(message-header-subject ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(message-header-to ((,class (:foreground ,(car nord9)))
                        (((type tty)) (:foreground ,(cdr nord9)))))
   `(message-header-xheader ((,class (:foreground ,(car nord13)))
                             (((type tty)) (:foreground ,(cdr nord13)))))
   `(message-mml ((,class (:foreground ,(car nord10)))
                  (((type tty)) (:foreground ,(cdr nord10)))))
   `(message-separator ((,class (:inherit shadow))
                        (((type tty)) (:inherit shadow))))
   `(minibuffer-prompt ((,class (:foreground ,(car nord8) :weight bold))
                        (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(mm-command-output ((,class (:foreground ,(car nord8)))
                        (((type tty)) (:foreground ,(cdr nord8)))))
   `(mode-line ((,class (:foreground ,(car nord8) :background ,(car nord3)))
                (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord3)))))
   `(mode-line-buffer-id ((,class (:weight bold))
                          (((type tty)) (:weight bold))))
   `(mode-line-highlight ((,class (:inherit highlight))
                          (((type tty)) (:inherit highlight))))
   `(mode-line-inactive ((,class (:foreground ,(car nord4) :background ,nord-uniform-mode-lines-background))
                         (((type tty)) (:foreground ,(cdr nord4) :background ,nord-uniform-mode-lines-background))))
   `(next-error ((,class (:inherit error))
                 (((type tty)) (:inherit error))))
   `(nobreak-space ((,class (:foreground ,(car nord3)))
                    (((type tty)) (:foreground ,(cdr nord3)))))
   `(outline-1 ((,class (:foreground ,(car nord8) :weight bold))
                (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(outline-2 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-3 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-4 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-5 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-6 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-7 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(outline-8 ((,class (:inherit outline-1))
                (((type tty)) (:inherit outline-1))))
   `(package-description ((,class (:foreground ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord4)))))
   `(package-help-section-name ((,class (:foreground ,(car nord8) :weight bold))
                                (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(package-name ((,class (:foreground ,(car nord8)))
                   (((type tty)) (:foreground ,(cdr nord8)))))
   `(package-status-available ((,class (:foreground ,(car nord7)))
                               (((type tty)) (:foreground ,(cdr nord7)))))
   `(package-status-avail-obso ((,class (:foreground ,(car nord7) :slant italic))
                                (((type tty)) (:foreground ,(cdr nord7) :slant italic))))
   `(package-status-built-in ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(package-status-dependency ((,class (:foreground ,(car nord8) :slant italic))
                                (((type tty)) (:foreground ,(cdr nord8) :slant italic))))
   `(package-status-disabled ((,class (:foreground ,(car nord3)))
                              (((type tty)) (:foreground ,(cdr nord3)))))
   `(package-status-external ((,class (:foreground ,(car nord12) :slant italic))
                              (((type tty)) (:foreground ,(cdr nord12) :slant italic))))
   `(package-status-held ((,class (:foreground ,(car nord4) :weight bold))
                          (((type tty)) (:foreground ,(cdr nord4) :weight bold))))
   `(package-status-new ((,class (:foreground ,(car nord14)))
                         (((type tty)) (:foreground ,(cdr nord14)))))
   `(package-status-incompat ((,class (:foreground ,(car nord11)))
                              (((type tty)) (:foreground ,(cdr nord11)))))
   `(package-status-installed ((,class (:foreground ,(car nord7) :weight bold))
                               (((type tty)) (:foreground ,(cdr nord7) :weight bold))))
   `(package-status-unsigned ((,class (:underline ,(car nord13)))
                              (((type tty)) (:underline ,(cdr nord13)))))
   `(query-replace ((,class (:foreground ,(car nord8) :background ,(car nord2)))
                    (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord2)))))
   `(region ((,class (:foreground ,nord-region-highlight-foreground :background ,nord-region-highlight-background))
             (((type tty)) (:foreground ,nord-region-highlight-foreground :background ,nord-region-highlight-background))))
   `(scroll-bar ((,class (:background ,(car nord3)))
                 (((type tty)) (:background ,(cdr nord3)))))
   `(secondary-selection ((,class (:background ,(car nord2)))
                          (((type tty)) (:background ,(cdr nord2)))))
   `(show-paren-match-face ((,class (:foreground ,(car nord0) :background ,(car nord8)))
                            (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord8)))))
   `(show-paren-mismatch-face ((,class (:background ,(car nord11)))
                               (((type tty)) (:background ,(cdr nord11)))))
   `(success ((,class (:foreground ,(car nord14)))
              (((type tty)) (:foreground ,(cdr nord14)))))
   `(term ((,class (:foreground ,(car nord4) :background ,(car nord0)))
           (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord0)))))
   `(term-color-black ((,class (:foreground ,(car nord1) :background ,(car nord1)))
                       (((type tty)) (:foreground ,(cdr nord1) :background ,(cdr nord1)))))
   `(term-color-white ((,class (:foreground ,(car nord5) :background ,(car nord5)))
                       (((type tty)) (:foreground ,(cdr nord5) :background ,(cdr nord5)))))
   `(term-color-cyan ((,class (:foreground ,(car nord7) :background ,(car nord7)))
                      (((type tty)) (:foreground ,(cdr nord7) :background ,(cdr nord7)))))
   `(term-color-blue ((,class (:foreground ,(car nord8) :background ,(car nord8)))
                      (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord8)))))
   `(term-color-red ((,class (:foreground ,(car nord11) :background ,(car nord11)))
                     (((type tty)) (:foreground ,(cdr nord11) :background ,(cdr nord11)))))
   `(term-color-yellow ((,class (:foreground ,(car nord13) :background ,(car nord13)))
                        (((type tty)) (:foreground ,(cdr nord13) :background ,(cdr nord13)))))
   `(term-color-green ((,class (:foreground ,(car nord14) :background ,(car nord14)))
                       (((type tty)) (:foreground ,(cdr nord14) :background ,(cdr nord14)))))
   `(term-color-magenta ((,class (:foreground ,(car nord15) :background ,(car nord15)))
                         (((type tty)) (:foreground ,(cdr nord15) :background ,(cdr nord15)))))
   `(tool-bar ((,class (:foreground ,(car nord4) :background ,(car nord3)))
               (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord3)))))
   `(tooltip ((,class (:foreground ,(car nord0) :background ,(car nord4)))
              (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord4)))))
   `(trailing-whitespace ((,class (:foreground ,(car nord3)))
                          (((type tty)) (:foreground ,(cdr nord3)))))
   `(tty-menu-disabled-face ((,class (:foreground ,(car nord1)))
                             (((type tty)) (:foreground ,(cdr nord1)))))
   `(tty-menu-enabled-face ((,class (:background ,(car nord2) foreground ,(car nord4)))
                            (((type tty)) (:background ,(cdr nord2) foreground ,(cdr nord4)))))
   `(tty-menu-selected-face ((,class (:foreground ,(car nord8) :underline t))
                             (((type tty)) (:foreground ,(cdr nord8) :underline t))))
   `(undo-tree-visualizer-current-face ((,class (:foreground ,(car nord8)))
                                        (((type tty)) (:foreground ,(cdr nord8)))))
   `(undo-tree-visualizer-default-face ((,class (:foreground ,(car nord4)))
                                        (((type tty)) (:foreground ,(cdr nord4)))))
   `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,(car nord4)))
                                           (((type tty)) (:foreground ,(cdr nord4)))))
   `(undo-tree-visualizer-register-face ((,class (:foreground ,(car nord9)))
                                         (((type tty)) (:foreground ,(cdr nord9)))))
   `(vc-conflict-state ((,class (:foreground ,(car nord12)))
                        (((type tty)) (:foreground ,(cdr nord12)))))
   `(vc-edited-state ((,class (:foreground ,(car nord13)))
                      (((type tty)) (:foreground ,(cdr nord13)))))
   `(vc-locally-added-state ((,class (:underline ,(car nord14)))
                             (((type tty)) (:underline ,(cdr nord14)))))
   `(vc-locked-state ((,class (:foreground ,(car nord10)))
                      (((type tty)) (:foreground ,(cdr nord10)))))
   `(vc-missing-state ((,class (:foreground ,(car nord11)))
                       (((type tty)) (:foreground ,(cdr nord11)))))
   `(vc-needs-update-state ((,class (:foreground ,(car nord12)))
                            (((type tty)) (:foreground ,(cdr nord12)))))
   `(vc-removed-state ((,class (:foreground ,(car nord11)))
                       (((type tty)) (:foreground ,(cdr nord11)))))
   `(vc-state-base ((,class (:foreground ,(car nord4)))
                    (((type tty)) (:foreground ,(cdr nord4)))))
   `(vc-up-to-date-state ((,class (:foreground ,(car nord8)))
                          (((type tty)) (:foreground ,(cdr nord8)))))
   `(vertical-border ((,class (:foreground ,(car nord2)))
                      (((type tty)) (:foreground ,(cdr nord2)))))
   `(which-func ((,class (:foreground ,(car nord8)))
                 (((type tty)) (:foreground ,(cdr nord8)))))
   `(whitespace-big-indent ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                            (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-empty ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                       (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-hspace ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                        (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-indentation ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                             (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-line ((,class (:background ,(car nord0)))
                      (((type tty)) (:background ,(cdr nord0)))))
   `(whitespace-newline ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                         (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-space ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                       (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-space-after-tab ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                                 (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-space-before-tab ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                                  (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-tab ((,class (:foreground ,(car nord3) :background ,(car nord0)))
                     (((type tty)) (:foreground ,(cdr nord3) :background ,(cdr nord0)))))
   `(whitespace-trailing ((,class (:inherit trailing-whitespace))
                          (((type tty)) (:inherit trailing-whitespace))))
   `(widget-button-pressed ((,class (:foreground ,(car nord9) :background ,(car nord1)))
                            (((type tty)) (:foreground ,(cdr nord9) :background ,(cdr nord1)))))
   `(widget-documentation ((,class (:foreground ,(car nord4)))
                           (((type tty)) (:foreground ,(cdr nord4)))))
   `(widget-field ((,class (:background ,(car nord2) :foreground ,(car nord4)))
                   (((type tty)) (:background ,(cdr nord2) :foreground ,(cdr nord4)))))
   `(widget-single-line-field ((,class (:background ,(car nord2) :foreground ,(car nord4)))
                               (((type tty)) (:background ,(cdr nord2) :foreground ,(cdr nord4)))))
   `(window-divider ((,class (:background ,(car nord3)))
                     (((type tty)) (:background ,(cdr nord3)))))
   `(window-divider-first-pixel ((,class (:background ,(car nord3)))
                                 (((type tty)) (:background ,(cdr nord3)))))
   `(window-divider-last-pixel ((,class (:background ,(car nord3)))
                                (((type tty)) (:background ,(cdr nord3)))))

    ;;;; +-----------------+
    ;;;; + Package Support +
    ;;;; +-----------------+
   ;; +--- Syntax ---+
   ;; > Auctex
   `(font-latex-bold-face ((,class (:inherit bold))
                           (((type tty)) (:inherit bold))))
   `(font-latex-italic-face ((,class (:inherit italic))
                             (((type tty)) (:inherit italic))))
   `(font-latex-math-face ((,class (:foreground ,(car nord8)))
                           (((type tty)) (:foreground ,(cdr nord8)))))
   `(font-latex-sectioning-0-face ((,class (:foreground ,(car nord8) :weight bold))
                                   (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))
                                   (((type tty)) (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))
                                   (((type tty)) (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))
                                   (((type tty)) (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))
                                   (((type tty)) (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))
                                   (((type tty)) (:inherit font-latex-sectioning-0-face))))
   `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))
                                  (((type tty)) (:inherit font-lock-warning-face))))
   `(font-latex-string-face ((,class (:inherit font-lock-string-face))
                             (((type tty)) (:inherit font-lock-string-face))))
   `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))
                              (((type tty)) (:inherit font-lock-warning-face))))

   ;; > Elixir
   `(elixir-attribute-face ((,class (:foreground ,(car nord-annotation)))
                            (((type tty)) (:foreground ,(cdr nord-annotation)))))
   `(elixir-atom-face ((,class (:foreground ,(car nord4) :weight bold))
                       (((type tty)) (:foreground ,(cdr nord4) :weight bold))))

   ;; > Enhanced Ruby
   `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,(car nord14)))
                                      (((type tty)) (:foreground ,(cdr nord14)))))
   `(enh-ruby-op-face ((,class (:foreground ,(car nord9)))
                       (((type tty)) (:foreground ,(cdr nord9)))))
   `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,(car nord13)))
                                     (((type tty)) (:foreground ,(cdr nord13)))))
   `(enh-ruby-regexp-face ((,class (:foreground ,(car nord13)))
                           (((type tty)) (:foreground ,(cdr nord13)))))
   `(enh-ruby-string-delimiter-face ((,class (:foreground ,(car nord14)))
                                     (((type tty)) (:foreground ,(cdr nord14)))))
   `(erm-syn-errline ((,class (:foreground ,(car nord11) :underline t))
                      (((type tty)) (:foreground ,(cdr nord11) :underline t))))
   `(erm-syn-warnline ((,class (:foreground ,(car nord13) :underline t))
                       (((type tty)) (:foreground ,(cdr nord13) :underline t))))

   ;; > Java Development Environment for Emacs
   `(jdee-db-active-breakpoint-face ((,class (:background ,(car nord2) :weight bold))
                                     (((type tty)) (:background ,(cdr nord2) :weight bold))))
   `(jdee-bug-breakpoint-cursor ((,class (:background ,(car nord2)))
                                 (((type tty)) (:background ,(cdr nord2)))))
   `(jdee-db-requested-breakpoint-face ((,class (:foreground ,(car nord13) :background ,(car nord2) :weight bold))
                                        (((type tty)) (:foreground ,(cdr nord13) :background ,(cdr nord2) :weight bold))))
   `(jdee-db-spec-breakpoint-face ((,class (:foreground ,(car nord14) :background ,(car nord2) :weight bold))
                                   (((type tty)) (:foreground ,(cdr nord14) :background ,(cdr nord2) :weight bold))))
   `(jdee-font-lock-api-face ((,class (:foreground ,(car nord4)))
                              (((type tty)) (:foreground ,(cdr nord4)))))
   `(jdee-font-lock-code-face ((,class (:slant italic))
                               (((type tty)) (:slant italic))))
   `(jdee-font-lock-constant-face ((,class (:foreground ,(car nord-keyword)))
                                   (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(jdee-font-lock-constructor-face ((,class (:foreground ,(car nord-method)))
                                      (((type tty)) (:foreground ,(cdr nord-method)))))
   `(jdee-font-lock-doc-tag-face ((,class (:foreground ,(car nord7)))
                                  (((type tty)) (:foreground ,(cdr nord7)))))
   `(jdee-font-lock-link-face ((,class (:underline t))
                               (((type tty)) (:underline t))))
   `(jdee-font-lock-modifier-face ((,class (:foreground ,(car nord-keyword)))
                                   (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(jdee-font-lock-number-face ((,class (:foreground ,(car nord-numeric)))
                                 (((type tty)) (:foreground ,(cdr nord-numeric)))))
   `(jdee-font-lock-operator-fac ((,class (:foreground ,(car nord-operator)))
                                  (((type tty)) (:foreground ,(cdr nord-operator)))))
   `(jdee-font-lock-package-face ((,class (:foreground ,(car nord-class)))
                                  (((type tty)) (:foreground ,(cdr nord-class)))))
   `(jdee-font-lock-pre-face ((,class (:foreground ,(car nord-comment) :slant italic))
                              (((type tty)) (:foreground ,(cdr nord-comment) :slant italic))))
   `(jdee-font-lock-private-face ((,class (:foreground ,(car nord-keyword)))
                                  (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(jdee-font-lock-public-face ((,class (:foreground ,(car nord-keyword)))
                                 (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(jdee-font-lock-variable-face ((,class (:foreground ,(car nord-variable)))
                                   (((type tty)) (:foreground ,(cdr nord-variable)))))

   ;; > JavaScript 2
   `(js2-function-call ((,class (:foreground ,(car nord8)))
                        (((type tty)) (:foreground ,(cdr nord8)))))
   `(js2-private-function-call ((,class (:foreground ,(car nord8)))
                                (((type tty)) (:foreground ,(cdr nord8)))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,(car nord6)))
                                   (((type tty)) (:foreground ,(cdr nord6)))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(js2-external-variable ((,class (:foreground ,(car nord4)))
                            (((type tty)) (:foreground ,(cdr nord4)))))
   `(js2-function-param ((,class (:foreground ,(car nord4)))
                         (((type tty)) (:foreground ,(cdr nord4)))))
   `(js2-jsdoc-value ((,class (:foreground ,(car nord-comment)))
                      (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(js2-jsdoc-tag ((,class (:foreground ,(car nord7)))
                    (((type tty)) (:foreground ,(cdr nord7)))))
   `(js2-jsdoc-type ((,class (:foreground ,(car nord7)))
                     (((type tty)) (:foreground ,(cdr nord7)))))
   `(js2-private-member ((,class (:foreground ,(car nord4)))
                         (((type tty)) (:foreground ,(cdr nord4)))))
   `(js2-object-property ((,class (:foreground ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord4)))))
   `(js2-error ((,class (:foreground ,(car nord11)))
                (((type tty)) (:foreground ,(cdr nord11)))))
   `(js2-warning ((,class (:foreground ,(car nord13)))
                  (((type tty)) (:foreground ,(cdr nord13)))))
   `(js2-instance-member ((,class (:foreground ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord4)))))

   ;; > JavaScript 3
   `(js3-error-face ((,class (:foreground ,(car nord11)))
                     (((type tty)) (:foreground ,(cdr nord11)))))
   `(js3-external-variable-face ((,class (:foreground ,(car nord4)))
                                 (((type tty)) (:foreground ,(cdr nord4)))))
   `(js3-function-param-face ((,class (:foreground ,(car nord4)))
                              (((type tty)) (:foreground ,(cdr nord4)))))
   `(js3-instance-member-face ((,class (:foreground ,(car nord4)))
                               (((type tty)) (:foreground ,(cdr nord4)))))
   `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,(car nord6)))
                                        (((type tty)) (:foreground ,(cdr nord6)))))
   `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,(car nord9)))
                                   (((type tty)) (:foreground ,(cdr nord9)))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,(car nord9)))
                         (((type tty)) (:foreground ,(cdr nord9)))))
   `(js3-jsdoc-type-face ((,class (:foreground ,(car nord7)))
                          (((type tty)) (:foreground ,(cdr nord7)))))
   `(js3-jsdoc-value-face ((,class (:foreground ,(car nord4)))
                           (((type tty)) (:foreground ,(cdr nord4)))))
   `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))
                           (((type tty)) (:inherit show-paren-match-face))))
   `(js3-private-function-call-face ((,class (:foreground ,(car nord8)))
                                     (((type tty)) (:foreground ,(cdr nord8)))))
   `(js3-private-member-face ((,class (:foreground ,(car nord4)))
                              (((type tty)) (:foreground ,(cdr nord4)))))
   `(js3-warning-face ((,class (:foreground ,(car nord13)))
                       (((type tty)) (:foreground ,(cdr nord13)))))

   ;; > Markdown
   `(markdown-blockquote-face ((,class (:foreground ,(car nord-comment)))
                               (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(markdown-bold-face ((,class (:inherit bold))
                         (((type tty)) (:inherit bold))))
   `(markdown-header-face-1 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-header-face-2 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-header-face-3 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-header-face-4 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-header-face-5 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-header-face-6 ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-inline-code-face ((,class (:foreground ,(car nord7)))
                                (((type tty)) (:foreground ,(cdr nord7)))))
   `(markdown-italic-face ((,class (:inherit italic))
                           (((type tty)) (:inherit italic))))
   `(markdown-link-face ((,class (:foreground ,(car nord8)))
                         (((type tty)) (:foreground ,(cdr nord8)))))
   `(markdown-markup-face ((,class (:foreground ,(car nord9)))
                           (((type tty)) (:foreground ,(cdr nord9)))))
   `(markdown-reference-face ((,class (:inherit markdown-link-face))
                              (((type tty)) (:inherit markdown-link-face))))
   `(markdown-url-face ((,class (:foreground ,(car nord4) :underline t))
                        (((type tty)) (:foreground ,(cdr nord4) :underline t))))

   ;; > Rainbow Delimeters
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,(car nord7))
                                      (((type tty)) :foreground ,(cdr nord7))))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,(car nord8))
                                      (((type tty)) :foreground ,(cdr nord8))))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,(car nord9))
                                      (((type tty)) :foreground ,(cdr nord9))))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,(car nord10))
                                      (((type tty)) :foreground ,(cdr nord10))))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,(car nord12))
                                      (((type tty)) :foreground ,(cdr nord12))))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,(car nord13))
                                      (((type tty)) :foreground ,(cdr nord13))))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,(car nord14))
                                      (((type tty)) :foreground ,(cdr nord14))))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,(car nord15))
                                      (((type tty)) :foreground ,(cdr nord15))))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,(car nord11))
                                        (((type tty)) :foreground ,(cdr nord11))))

   ;; > Web Mode
   `(web-mode-attr-tag-custom-face ((,class (:foreground ,(car nord-attribute)))
                                    (((type tty)) (:foreground ,(cdr nord-attribute)))))
   `(web-mode-builtin-face ((,class (:foreground ,(car nord-keyword)))
                            (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-comment-face ((,class (:foreground ,(car nord-comment)))
                            (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(web-mode-comment-keyword-face ((,class (:foreground ,(car nord-comment)))
                                    (((type tty)) (:foreground ,(cdr nord-comment)))))
   `(web-mode-constant-face ((,class (:foreground ,(car nord-variable)))
                             (((type tty)) (:foreground ,(cdr nord-variable)))))
   `(web-mode-css-at-rule-face ((,class (:foreground ,(car nord-annotation)))
                                (((type tty)) (:foreground ,(cdr nord-annotation)))))
   `(web-mode-css-function-face ((,class (:foreground ,(car nord-method)))
                                 (((type tty)) (:foreground ,(cdr nord-method)))))
   `(web-mode-css-property-name-face ((,class (:foreground ,(car nord-keyword)))
                                      (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-css-pseudo-class-face ((,class (:foreground ,(car nord-class)))
                                     (((type tty)) (:foreground ,(cdr nord-class)))))
   `(web-mode-css-selector-face ((,class (:foreground ,(car nord-keyword)))
                                 (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-css-string-face ((,class (:foreground ,(car nord-string)))
                               (((type tty)) (:foreground ,(cdr nord-string)))))
   `(web-mode-doctype-face ((,class (:foreground ,(car nord-preprocessor)))
                            (((type tty)) (:foreground ,(cdr nord-preprocessor)))))
   `(web-mode-function-call-face ((,class (:foreground ,(car nord-method)))
                                  (((type tty)) (:foreground ,(cdr nord-method)))))
   `(web-mode-function-name-face ((,class (:foreground ,(car nord-method)))
                                  (((type tty)) (:foreground ,(cdr nord-method)))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,(car nord-attribute)))
                                   (((type tty)) (:foreground ,(cdr nord-attribute)))))
   `(web-mode-html-attr-equal-face ((,class (:foreground ,(car nord-punctuation)))
                                    (((type tty)) (:foreground ,(cdr nord-punctuation)))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,(car nord-string)))
                                    (((type tty)) (:foreground ,(cdr nord-string)))))
   `(web-mode-html-entity-face ((,class (:foreground ,(car nord-keyword)))
                                (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,(car nord-punctuation)))
                                     (((type tty)) (:foreground ,(cdr nord-punctuation)))))
   `(web-mode-html-tag-custom-face ((,class (:foreground ,(car nord-tag)))
                                    (((type tty)) (:foreground ,(cdr nord-tag)))))
   `(web-mode-html-tag-face ((,class (:foreground ,(car nord-tag)))
                             (((type tty)) (:foreground ,(cdr nord-tag)))))
   `(web-mode-html-tag-namespaced-face ((,class (:foreground ,(car nord-keyword)))
                                        (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-json-key-face ((,class (:foreground ,(car nord-class)))
                             (((type tty)) (:foreground ,(cdr nord-class)))))
   `(web-mode-json-string-face ((,class (:foreground ,(car nord-string)))
                                (((type tty)) (:foreground ,(cdr nord-string)))))
   `(web-mode-keyword-face ((,class (:foreground ,(car nord-keyword)))
                            (((type tty)) (:foreground ,(cdr nord-keyword)))))
   `(web-mode-preprocessor-face ((,class (:foreground ,(car nord-preprocessor)))
                                 (((type tty)) (:foreground ,(cdr nord-preprocessor)))))
   `(web-mode-string-face ((,class (:foreground ,(car nord-string)))
                           (((type tty)) (:foreground ,(cdr nord-string)))))
   `(web-mode-symbol-face ((,class (:foreground ,(car nord-variable)))
                           (((type tty)) (:foreground ,(cdr nord-variable)))))
   `(web-mode-type-face ((,class (:foreground ,(car nord-class)))
                         (((type tty)) (:foreground ,(cdr nord-class)))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))
                            (((type tty)) (:inherit ,font-lock-warning-face))))
   `(web-mode-variable-name-face ((,class (:foreground ,(car nord-variable)))
                                  (((type tty)) (:foreground ,(cdr nord-variable)))))

   ;; +--- UI ---+
   ;; > Anzu
   `(anzu-mode-line ((,class (:foreground, (car nord8)))
                     (((type tty)) (:foreground, (cdr nord8)))))
   `(anzu-mode-line-no-match ((,class (:foreground, (car nord11)))
                              (((type tty)) (:foreground, (cdr nord11)))))

   ;; > Avy
   `(avy-lead-face ((,class (:background ,(car nord11) :foreground ,(car nord5)))
                    (((type tty)) (:background ,(cdr nord11) :foreground ,(cdr nord5)))))
   `(avy-lead-face-0 ((,class (:background ,(car nord10) :foreground ,(car nord5)))
                      (((type tty)) (:background ,(cdr nord10) :foreground ,(cdr nord5)))))
   `(avy-lead-face-1 ((,class (:background ,(car nord3) :foreground ,(car nord5)))
                      (((type tty)) (:background ,(cdr nord3) :foreground ,(cdr nord5)))))
   `(avy-lead-face-2 ((,class (:background ,(car nord15) :foreground ,(car nord5)))
                      (((type tty)) (:background ,(cdr nord15) :foreground ,(cdr nord5)))))

   ;; > Company
   `(company-echo-common ((,class (:foreground ,(car nord0) :background ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord4)))))
   `(company-preview ((,class (:foreground ,(car nord4) :background ,(car nord10)))
                      (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord10)))))
   `(company-preview-common ((,class (:foreground ,(car nord0) :background ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord8)))))
   `(company-preview-search ((,class (:foreground ,(car nord0) :background ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord8)))))
   `(company-scrollbar-bg ((,class (:foreground ,(car nord1) :background ,(car nord1)))
                           (((type tty)) (:foreground ,(cdr nord1) :background ,(cdr nord1)))))
   `(company-scrollbar-fg ((,class (:foreground ,(car nord2) :background ,(car nord2)))
                           (((type tty)) (:foreground ,(cdr nord2) :background ,(cdr nord2)))))
   `(company-template-field ((,class (:foreground ,(car nord0) :background ,(car nord7)))
                             (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord7)))))
   `(company-tooltip ((,class (:foreground ,(car nord4) :background ,(car nord2)))
                      (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord2)))))
   `(company-tooltip-annotation ((,class (:foreground ,(car nord12)))
                                 (((type tty)) (:foreground ,(cdr nord12)))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,(car nord12) :weight bold))
                                           (((type tty)) (:foreground ,(cdr nord12) :weight bold))))
   `(company-tooltip-common ((,class (:foreground ,(car nord8)))
                             (((type tty)) (:foreground ,(cdr nord8)))))
   `(company-tooltip-common-selection ((,class (:foreground ,(car nord8) :background ,(car nord3)))
                                       (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord3)))))
   `(company-tooltip-mouse ((,class (:inherit highlight))
                            (((type tty)) (:inherit highlight))))
   `(company-tooltip-selection ((,class (:background ,(car nord3) :weight bold))
                                (((type tty)) (:background ,(cdr nord3) :weight bold))))

   ;; > diff-hl
   `(diff-hl-change ((,class (:background ,(car nord13)))
                     (((type tty)) (:background ,(cdr nord13)))))
   `(diff-hl-insert ((,class (:background ,(car nord14)))
                     (((type tty)) (:background ,(cdr nord14)))))
   `(diff-hl-delete ((,class (:background ,(car nord11)))
                     (((type tty)) (:background ,(cdr nord11)))))

   ;; > Evil
   `(evil-ex-info ((,class (:foreground ,(car nord8)))
                   (((type tty)) (:foreground ,(cdr nord8)))))
   `(evil-ex-substitute-replacement ((,class (:foreground ,(car nord9)))
                                     (((type tty)) (:foreground ,(cdr nord9)))))
   `(evil-ex-substitute-matches ((,class (:inherit isearch))
                                 (((type tty)) (:inherit isearch))))

   ;; > Flycheck
   `(flycheck-error ((,class (:underline (:style wave :color ,(car nord11))))
                     (((type tty)) (:underline (:style wave :color ,(cdr nord11))))))
   `(flycheck-fringe-error ((,class (:foreground ,(car nord11) :weight bold))
                            (((type tty)) (:foreground ,(cdr nord11) :weight bold))))
   `(flycheck-fringe-info ((,class (:foreground ,(car nord8) :weight bold))
                           (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(flycheck-fringe-warning ((,class (:foreground ,(car nord13) :weight bold))
                              (((type tty)) (:foreground ,(cdr nord13) :weight bold))))
   `(flycheck-info ((,class (:underline (:style wave :color ,(car nord8))))
                    (((type tty)) (:underline (:style wave :color ,(cdr nord8))))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,(car nord13))))
                       (((type tty)) (:underline (:style wave :color ,(cdr nord13))))))

   ;; > Git Gutter
   `(git-gutter:modified ((,class (:foreground ,(car nord13)))
                          (((type tty)) (:foreground ,(cdr nord13)))))
   `(git-gutter:added ((,class (:foreground ,(car nord14)))
                       (((type tty)) (:foreground ,(cdr nord14)))))
   `(git-gutter:deleted ((,class (:foreground ,(car nord11)))
                         (((type tty)) (:foreground ,(cdr nord11)))))

   ;; > Git Gutter Plus
   `(git-gutter+-modified ((,class (:foreground ,(car nord13)))
                           (((type tty)) (:foreground ,(cdr nord13)))))
   `(git-gutter+-added ((,class (:foreground ,(car nord14)))
                        (((type tty)) (:foreground ,(cdr nord14)))))
   `(git-gutter+-deleted ((,class (:foreground ,(car nord11)))
                          (((type tty)) (:foreground ,(cdr nord11)))))

   ;; > Helm
   `(helm-bookmark-addressbook ((,class (:foreground ,(car nord7)))
                                (((type tty)) (:foreground ,(cdr nord7)))))
   `(helm-bookmark-directory ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(helm-bookmark-file ((,class (:foreground ,(car nord8)))
                         (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-bookmark-gnus ((,class (:foreground ,(car nord10)))
                         (((type tty)) (:foreground ,(cdr nord10)))))
   `(helm-bookmark-info ((,class (:foreground ,(car nord14)))
                         (((type tty)) (:foreground ,(cdr nord14)))))
   `(helm-bookmark-man ((,class (:foreground ,(car nord4)))
                        (((type tty)) (:foreground ,(cdr nord4)))))
   `(helm-bookmark-w3m ((,class (:foreground ,(car nord9)))
                        (((type tty)) (:foreground ,(cdr nord9)))))
   `(helm-buffer-directory ((,class (:foreground ,(car nord9)))
                            (((type tty)) (:foreground ,(cdr nord9)))))
   `(helm-buffer-file ((,class (:foreground ,(car nord8)))
                       (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-buffer-not-saved ((,class (:foreground ,(car nord13)))
                            (((type tty)) (:foreground ,(cdr nord13)))))
   `(helm-buffer-process ((,class (:foreground ,(car nord10)))
                          (((type tty)) (:foreground ,(cdr nord10)))))
   `(helm-candidate-number ((,class (:foreground ,(car nord4) :weight bold))
                            (((type tty)) (:foreground ,(cdr nord4) :weight bold))))
   `(helm-candidate-number-suspended ((,class (:foreground ,(car nord4)))
                                      (((type tty)) (:foreground ,(cdr nord4)))))
   `(helm-ff-directory ((,class (:foreground ,(car nord9) :weight bold))
                        (((type tty)) (:foreground ,(cdr nord9) :weight bold))))
   `(helm-ff-dirs ((,class (:foreground ,(car nord9)))
                   (((type tty)) (:foreground ,(cdr nord9)))))
   `(helm-ff-dotted-director ((,class (:foreground ,(car nord9) :underline t))
                              (((type tty)) (:foreground ,(cdr nord9) :underline t))))
   `(helm-ff-dotted-symlink-director ((,class (:foreground ,(car nord7) :weight bold))
                                      (((type tty)) (:foreground ,(cdr nord7) :weight bold))))
   `(helm-ff-executable ((,class (:foreground ,(car nord8)))
                         (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-ff-file ((,class (:foreground ,(car nord4)))
                   (((type tty)) (:foreground ,(cdr nord4)))))
   `(helm-ff-invalid-symlink ((,class (:foreground ,(car nord11) :weight bold))
                              (((type tty)) (:foreground ,(cdr nord11) :weight bold))))
   `(helm-ff-prefix ((,class (:foreground ,(car nord0) :background ,(car nord9)))
                     (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord9)))))
   `(helm-ff-symlink ((,class (:foreground ,(car nord7)))
                      (((type tty)) (:foreground ,(cdr nord7)))))
   `(helm-grep-cmd-line ((,class (:foreground ,(car nord4) :background ,(car nord0)))
                         (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord0)))))
   `(helm-grep-file ((,class (:foreground ,(car nord8)))
                     (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-grep-finish ((,class (:foreground ,(car nord5)))
                       (((type tty)) (:foreground ,(cdr nord5)))))
   `(helm-grep-lineno ((,class (:foreground ,(car nord4)))
                       (((type tty)) (:foreground ,(cdr nord4)))))
   `(helm-grep-match ((,class (:inherit isearch))
                      (((type tty)) (:inherit isearch))))
   `(helm-grep-running ((,class (:foreground ,(car nord8)))
                        (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-header ((,class (:foreground ,(car nord9) :background ,(car nord2)))
                  (((type tty)) (:foreground ,(cdr nord9) :background ,(cdr nord2)))))
   `(helm-header-line-left-margin ((,class (:foreground ,(car nord9) :background ,(car nord2)))
                                   (((type tty)) (:foreground ,(cdr nord9) :background ,(cdr nord2)))))
   `(helm-history-deleted ((,class (:foreground ,(car nord11)))
                           (((type tty)) (:foreground ,(cdr nord11)))))
   `(helm-history-remote ((,class (:foreground ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord4)))))
   `(helm-lisp-completion-info ((,class (:foreground ,(car nord4) :weight bold))
                                (((type tty)) (:foreground ,(cdr nord4) :weight bold))))
   `(helm-lisp-show-completion ((,class (:inherit isearch))
                                (((type tty)) (:inherit isearch))))
   `(helm-locate-finish ((,class (:foreground ,(car nord14)))
                         (((type tty)) (:foreground ,(cdr nord14)))))
   `(helm-match ((,class (:foreground ,(car nord8)))
                 (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-match-item ((,class (:inherit isearch))
                      (((type tty)) (:inherit isearch))))
   `(helm-moccur-buffer ((,class (:foreground ,(car nord8)))
                         (((type tty)) (:foreground ,(cdr nord8)))))
   `(helm-resume-need-update ((,class (:foreground ,(car nord0) :background ,(car nord13)))
                              (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord13)))))
   `(helm-selection ((,class (:inherit highlight))
                     (((type tty)) (:inherit highlight))))
   `(helm-selection-line ((,class (:background ,(car nord2)))
                          (((type tty)) (:background ,(cdr nord2)))))
   `(helm-source-header ((,class (:height 1.44 :foreground ,(car nord8) :background ,(car nord2)))
                         (((type tty)) (:height 1.44 :foreground ,(cdr nord8) :background ,(cdr nord2)))))
   `(helm-swoop-line-number-face ((,class (:foreground ,(car nord4) :background ,(car nord0)))
                                  (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord0)))))
   `(helm-swoop-target-word-face ((,class (:foreground ,(car nord0) :background ,(car nord7)))
                                  (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord7)))))
   `(helm-swoop-target-line-face ((,class (:background ,(car nord13) :foreground ,(car nord3)))
                                  (((type tty)) (:background ,(cdr nord13) :foreground ,(cdr nord3)))))
   `(helm-swoop-target-line-block-face ((,class (:background ,(car nord13) :foreground ,(car nord3)))
                                        (((type tty)) (:background ,(cdr nord13) :foreground ,(cdr nord3)))))
   `(helm-separator ((,class (:background ,(car nord2)))
                     (((type tty)) (:background ,(cdr nord2)))))
   `(helm-visible-mark ((,class (:background ,(car nord2)))
                        (((type tty)) (:background ,(cdr nord2)))))

   ;; > Magit
   `(magit-branch ((,class (:foreground ,(car nord7) :weight bold))
                   (((type tty)) (:foreground ,(cdr nord7) :weight bold))))
   `(magit-diff-context-highlight ((,class (:background ,(car nord2)))
                                   (((type tty)) (:background ,(cdr nord2)))))
   `(magit-diff-file-header ((,class (:foreground ,(car nord8) :box (:color ,(car nord8))))
                             (((type tty)) (:foreground ,(cdr nord8) :box (:color ,(cdr nord8))))))
   `(magit-diffstat-added ((,class (:foreground ,(car nord14)))
                           (((type tty)) (:foreground ,(cdr nord14)))))
   `(magit-diffstat-removed ((,class (:foreground ,(car nord11)))
                             (((type tty)) (:foreground ,(cdr nord11)))))
   `(magit-hash ((,class (:foreground ,(car nord8)))
                 (((type tty)) (:foreground ,(cdr nord8)))))
   `(magit-hunk-heading ((,class (:foreground ,(car nord9)))
                         (((type tty)) (:foreground ,(cdr nord9)))))
   `(magit-hunk-heading-highlight ((,class (:foreground ,(car nord9) :background ,(car nord2)))
                                   (((type tty)) (:foreground ,(cdr nord9) :background ,(cdr nord2)))))
   `(magit-item-highlight ((,class (:foreground ,(car nord8) :background ,(car nord2)))
                           (((type tty)) (:foreground ,(cdr nord8) :background ,(cdr nord2)))))
   `(magit-log-author ((,class (:foreground ,(car nord7)))
                       (((type tty)) (:foreground ,(cdr nord7)))))
   `(magit-process-ng ((,class (:foreground ,(car nord13) :weight bold))
                       (((type tty)) (:foreground ,(cdr nord13) :weight bold))))
   `(magit-process-ok ((,class (:foreground ,(car nord14) :weight bold))
                       (((type tty)) (:foreground ,(cdr nord14) :weight bold))))
   `(magit-section-heading ((,class (:foreground ,(car nord7) :weight bold))
                            (((type tty)) (:foreground ,(cdr nord7) :weight bold))))
   `(magit-section-highlight ((,class (:background ,(car nord2)))
                              (((type tty)) (:background ,(cdr nord2)))))

   ;; > MU4E
   `(mu4e-header-marks-face ((,class (:foreground ,(car nord9)))
                             (((type tty)) (:foreground ,(cdr nord9)))))
   `(mu4e-title-face ((,class (:foreground ,(car nord8)))
                      (((type tty)) (:foreground ,(cdr nord8)))))
   `(mu4e-header-key-face ((,class (:foreground ,(car nord8)))
                           (((type tty)) (:foreground ,(cdr nord8)))))
   `(mu4e-highlight-face ((,class (:highlight))
                          (((type tty)) (:highlight))))
   `(mu4e-flagged-face ((,class (:foreground ,(car nord13)))
                        (((type tty)) (:foreground ,(cdr nord13)))))
   `(mu4e-unread-face ((,class (:foreground ,(car nord13) :weight bold))
                       (((type tty)) (:foreground ,(cdr nord13) :weight bold))))
   `(mu4e-link-face ((,class (:underline t))
                     (((type tty)) (:underline t))))

   ;; > Powerline
   `(powerline-active1 ((,class (:foreground ,(car nord4) :background ,(car nord1)))
                        (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord1)))))
   `(powerline-active2 ((,class (:foreground ,(car nord4) :background ,(car nord3)))
                        (((type tty)) (:foreground ,(cdr nord4) :background ,(cdr nord3)))))
   `(powerline-inactive1 ((,class (:background ,(car nord2)))
                          (((type tty)) (:background ,(cdr nord2)))))
   `(powerline-inactive2 ((,class (:background ,(car nord2)))
                          (((type tty)) (:background ,(cdr nord2)))))

   ;; > Powerline Evil
   `(powerline-evil-base-face ((,class (:foreground ,(car nord4)))
                               (((type tty)) (:foreground ,(cdr nord4)))))
   `(powerline-evil-normal-face ((,class (:background ,(car nord8)))
                                 (((type tty)) (:background ,(cdr nord8)))))
   `(powerline-evil-insert-face ((,class (:foreground ,(car nord0) :background ,(car nord4)))
                                 (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord4)))))
   `(powerline-evil-visual-face ((,class (:foreground ,(car nord0) :background ,(car nord7)))
                                 (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord7)))))
   `(powerline-evil-replace-face ((,class (:foreground ,(car nord0) :background ,(car nord9)))
                                  (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord9)))))

   ;; > NeoTree
   `(neo-banner-face ((,class (:foreground ,(car nord10)))
                      (((type tty)) (:foreground ,(cdr nord10)))))
   `(neo-dir-link-face ((,class (:foreground ,(car nord9)))
                        (((type tty)) (:foreground ,(cdr nord9)))))
   `(neo-expand-btn-face ((,class (:foreground ,(car nord6) :bold t))
                          (((type tty)) (:foreground ,(cdr nord6) :bold t))))
   `(neo-file-link-face ((,class (:foreground ,(car nord4)))
                         (((type tty)) (:foreground ,(cdr nord4)))))
   `(neo-root-dir-face ((,class (:foreground ,(car nord7) :weight bold))
                        (((type tty)) (:foreground ,(cdr nord7) :weight bold))))
   `(neo-vc-added-face ((,class (:foreground ,(car nord14)))
                        (((type tty)) (:foreground ,(cdr nord14)))))
   `(neo-vc-conflict-face ((,class (:foreground ,(car nord11)))
                           (((type tty)) (:foreground ,(cdr nord11)))))
   `(neo-vc-default-face ((,class (:foreground ,(car nord4)))
                          (((type tty)) (:foreground ,(cdr nord4)))))
   `(neo-vc-edited-face ((,class (:foreground ,(car nord13)))
                         (((type tty)) (:foreground ,(cdr nord13)))))
   `(neo-vc-ignored-face ((,class (:foreground ,(car nord3)))
                          (((type tty)) (:foreground ,(cdr nord3)))))
   `(neo-vc-missing-face ((,class (:foreground ,(car nord12)))
                          (((type tty)) (:foreground ,(cdr nord12)))))
   `(neo-vc-needs-merge-face ((,class (:background ,(car nord12) :foreground ,(car nord4)))
                              (((type tty)) (:background ,(cdr nord12) :foreground ,(cdr nord4)))))
   `(neo-vc-needs-update-face ((,class (:background ,(car nord10) :foreground ,(car nord4)))
                               (((type tty)) (:background ,(cdr nord10) :foreground ,(cdr nord4)))))
   `(neo-vc-removed-face ((,class (:foreground ,(car nord11) :strike-through nil))
                          (((type tty)) (:foreground ,(cdr nord11) :strike-through nil))))
   `(neo-vc-up-to-date-face ((,class (:foreground ,(car nord4)))
                             (((type tty)) (:foreground ,(cdr nord4)))))
   `(neo-vc-user-face ((,class (:foreground ,(car nord4)))
                       (((type tty)) (:foreground ,(cdr nord4)))))

   ;; > Org
   `(org-level-1 ((,class (:foreground ,(car nord8) :weight bold))
                  (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(org-level-2 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-3 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-4 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-5 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-6 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-7 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-level-8 ((,class (:inherit org-level-1))
                  (((type tty)) (:inherit org-level-1))))
   `(org-agenda-structure ((,class (:foreground ,(car nord9)))
                           (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-agenda-date ((,class (:foreground ,(car nord8) :underline nil))
                      (((type tty)) (:foreground ,(cdr nord8) :underline nil))))
   `(org-agenda-done ((,class (:foreground ,(car nord14)))
                      (((type tty)) (:foreground ,(cdr nord14)))))
   `(org-agenda-dimmed-todo-face ((,class (:background ,(car nord13)))
                                  (((type tty)) (:background ,(cdr nord13)))))
   `(org-block ((,class (:foreground ,(car nord4)))
                (((type tty)) (:foreground ,(cdr nord4)))))
   `(org-block-background ((,class (:background ,(car nord0)))
                           (((type tty)) (:background ,(cdr nord0)))))
   `(org-block-begin-line ((,class (:foreground ,(car nord7)))
                           (((type tty)) (:foreground ,(cdr nord7)))))
   `(org-block-end-line ((,class (:foreground ,(car nord7)))
                         (((type tty)) (:foreground ,(cdr nord7)))))
   `(org-checkbox ((,class (:foreground ,(car nord9)))
                   (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-checkbox-statistics-done ((,class (:foreground ,(car nord14)))
                                   (((type tty)) (:foreground ,(cdr nord14)))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,(car nord13)))
                                   (((type tty)) (:foreground ,(cdr nord13)))))
   `(org-code ((,class (:foreground ,(car nord7)))
               (((type tty)) (:foreground ,(cdr nord7)))))
   `(org-column ((,class (:background ,(car nord2)))
                 (((type tty)) (:background ,(cdr nord2)))))
   `(org-column-title ((,class (:inherit org-column :weight bold :underline t))
                       (((type tty)) (:inherit org-column :weight bold :underline t))))
   `(org-date ((,class (:foreground ,(car nord8)))
               (((type tty)) (:foreground ,(cdr nord8)))))
   `(org-document-info ((,class (:foreground ,(car nord4)))
                        (((type tty)) (:foreground ,(cdr nord4)))))
   `(org-document-info-keyword ((,class (:foreground ,(car nord3) :weight bold))
                                (((type tty)) (:foreground ,(cdr nord3) :weight bold))))
   `(org-document-title ((,class (:foreground ,(car nord8) :weight bold))
                         (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(org-done ((,class (:foreground ,(car nord14) :weight bold))
               (((type tty)) (:foreground ,(cdr nord14) :weight bold))))
   `(org-ellipsis ((,class (:foreground ,(car nord3)))
                   (((type tty)) (:foreground ,(cdr nord3)))))
   `(org-footnote ((,class (:foreground ,(car nord8)))
                   (((type tty)) (:foreground ,(cdr nord8)))))
   `(org-formula ((,class (:foreground ,(car nord9)))
                  (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-hide ((,class (:foreground ,(car nord0) :background ,(car nord0)))
               (((type tty)) (:foreground ,(cdr nord0) :background ,(cdr nord0)))))
   `(org-link ((,class (:underline t))
               (((type tty)) (:underline t))))
   `(org-scheduled ((,class (:foreground ,(car nord14)))
                    (((type tty)) (:foreground ,(cdr nord14)))))
   `(org-scheduled-previously ((,class (:foreground ,(car nord13)))
                               (((type tty)) (:foreground ,(cdr nord13)))))
   `(org-scheduled-today ((,class (:foreground ,(car nord8)))
                          (((type tty)) (:foreground ,(cdr nord8)))))
   `(org-special-keyword ((,class (:foreground ,(car nord9)))
                          (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-table ((,class (:foreground ,(car nord9)))
                (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-todo ((,class (:foreground ,(car nord13) :weight bold))
               (((type tty)) (:foreground ,(cdr nord13) :weight bold))))
   `(org-upcoming-deadline ((,class (:foreground ,(car nord12)))
                            (((type tty)) (:foreground ,(cdr nord12)))))
   `(org-warning ((,class (:foreground ,(car nord13) :weight bold))
                  (((type tty)) (:foreground ,(cdr nord13) :weight bold))))
   `(font-latex-bold-face ((,class (:inherit bold))
                           (((type tty)) (:inherit bold))))
   `(font-latex-italic-face ((,class (:slant italic))
                             (((type tty)) (:slant italic))))
   `(font-latex-string-face ((,class (:foreground ,(car nord14)))
                             (((type tty)) (:foreground ,(cdr nord14)))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,(car nord9)))
                                          (((type tty)) (:foreground ,(cdr nord9)))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,(car nord4)))
                                         (((type tty)) (:foreground ,(cdr nord4)))))
   `(ido-only-match ((,class (:foreground ,(car nord8)))
                     (((type tty)) (:foreground ,(cdr nord8)))))
   `(org-sexp-date ((,class (:foreground ,(car nord7)))
                    (((type tty)) (:foreground ,(cdr nord7)))))
   `(ido-first-match ((,class (:foreground ,(car nord8) :weight bold))
                      (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(ido-subdir ((,class (:foreground ,(car nord9)))
                 (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-quote ((,class (:inherit org-block :slant italic))
                (((type tty)) (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))
                (((type tty)) (:inherit org-block :slant italic))))
   `(org-agenda-date-weekend ((,class (:foreground ,(car nord9)))
                              (((type tty)) (:foreground ,(cdr nord9)))))
   `(org-agenda-date-today ((,class (:foreground ,(car nord8) :weight bold))
                            (((type tty)) (:foreground ,(cdr nord8) :weight bold))))
   `(org-agenda-done ((,class (:foreground ,(car nord14)))
                      (((type tty)) (:foreground ,(cdr nord14)))))
   `(org-verbatim ((,class (:foreground ,(car nord7)))
                   (((type tty)) (:foreground ,(cdr nord7)))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'nord)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; nord-theme.el ends here
